### ISSUE TITLE
Plugin Concept: Twitch

### ISSUE THREAD

**Issue by julxyz** [juliscrazy/Peach#20]
Heavily inspired by [maikdevries/Lunar](https://github.com/maikdevries/Lunar)

Add livestream announcements. When livestream is offline turn announcement into link to vod,

**Comment by julxyz** [comment]
Also make sure to add this: maikdevries/Lunar#7

**Comment by julxyz** [comment]
Thumbnails n previews n stuff should be cached via discordcdn using some discord server with a channel specified for this

**Comment by maikdevries** [comment]
Given that using a Discord channel as CDN is against Discord's ToS, I was in search for a solution to a similar problem. The solution is simple and easy to implement: https://github.com/maikdevries/Lunar/issues/21
