### ISSUE TITLE
Plugin Concept: Ping+

### ISSUE THREAD

**Issue by julxyz** [juliscrazy/Peach#9]
### Problem
In discord a role can only be made mentionable for everyone or nobody at all. If you want to make an announcement role for example, everyone will be able to ping it.

### Proposed Solution
A command like !ping @role <message> that makes the bot echo the message. To ping the role the bot changes the roles permission to be pinged just for so long that the message can be sent. Directly after that the bot makes the role unmentinable again.

### Alternatives
An alternative to this is pinging @everyone which is generally a bad idea unless you have something very important to say.

**Comment by maikdevries** [comment]
With a recent change in ping permissions, it's no longer necessarily the case that everyone can ping pingable roles.

By disabling the 'Allow anyone to @mention this role' permission for such role, the masses are prevented from pinging it. However, by granting the 'Mention @everyone, @here and All Roles' to people will allow those to still ping these roles.
![image](https://user-images.githubusercontent.com/44983425/83456696-75e55180-a460-11ea-9008-80bfc9edbcfd.png)
